---
title: "In-class_Ex9"
date: "March 9,2024"
date-modified: "last-modified"
execute: 
  eval: true 
  echo: true
  message: false
  warning: false
editor: visual 
---

```{r}
pacman::p_load(igraph, tidygraph, ggraph, 
               visNetwork, lubridate, clock,
               tidyverse, graphlayouts)
```

```{r}
GAStech_nodes <- read_csv("data/GAStech_email_node.csv")
GAStech_edges <- read_csv("data/GAStech_email_edge-v2.csv")

```

```{r}
GAStech_edges <- GAStech_edges %>%
  mutate(SendDate= dmy(SentDate)) %>%
  mutate(Weekday= wday(SentDate,
                       label= TRUE,
                       abbr= FALSE))
```

```{r}
GAStech_edges_aggregated <- GAStech_edges %>%
  filter(MainSubject =='Work related') %>%
  group_by (source, target, Weekday) %>%
    summarise(Weight = n()) %>%
  filter(source!= target) %>%
  filter(Weight >1) %>%
  ungroup()
```

```{r}
GAStech_graph <- tbl_graph(nodes =
                             GAStech_nodes,
                           edges=
                             GAStech_edges_aggregated,
                           directed = TRUE)
```

```{r}
ggraph(GAStech_graph) +
  geom_edge_link() +
  geom_node_point()
```

```{r}
g <- ggraph(GAStech_graph, 
            layout = "nicely") +
  geom_edge_link(aes(width=Weight),
                 alpha= 0.2) +
  scale_edge_width(range = c(0.1,5)) +
  geom_node_point(aes(color= Department,
                      size =3))

g + theme_graph()
```

```{r}
g <- ggraph(GAStech_graph, 
            layout = "nicely") +
  geom_edge_link(aes(width=Weight),
                 alpha= 0.2) +
  scale_edge_width(range = c(0.1,5)) +
  geom_node_point(aes(color= Department,
                      size =3))

g + facet_edges(~Weekday)
```
